spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/transportador
    username: postgres
    password: 123456
    driverClassName: org.postgresql.Driver
    hikari:
      schema: public
      maximum-pool-size: 50
      minimum-idle: 10
      connection-test-query: SELECT 1
      data-source-properties:
        connectTimeout: 3000
        socketTimeout: 3000
        
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect

flyway:
  locations: classpath:db/migration
  schemas: public
  baselineOnMigrate: true
  validateOnMigrate: false 
